### ISSUE TITLE
shiny.express.ui.input_file does not report value to client

### ISSUE THREAD

**Issue by roivant-matts** [posit-dev/py-shiny#1333]
I attempted to conditionally render ui elements based on the value of a input value from an input_file ui element (browse for file). When I log the input values on the client side I can see the file input variable stays as null. Is this expected? If it is expected, is there another way I can conditionally render based on the input value created from an input_file?

**Comment by gadenbuie** [comment]
Hi @roivant-matts, can you please provide a minimal, reproducible example? You can use https://shinylive.io/py/editor as a fast way to create the example. Shinylive.io has a Share button the provides a link you can drop into this thread. Thanks!

**Comment by roivant-matts** [comment]
Sure.
[https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbDOAD1R04LFkw4xUxOmTERUAVzJ4m8jsqEQAJnDoAdCPUatO3DGWyphYiVJkAxDgBs4ASQPF9+1VigBzOAD6xKhkLAAU+kxRTGQcZM4AvLpgAKJ8sKjOyXiR0TROjlAARokAKnTycDkQAJSeEF4cGFwKZAH5zhEQ0UzJHXAAjNm5UckAwmzExCxwTA5Z+CNMUISEcCEJwMkYhCwAbskAutU9MPKOsZlwCXZQjjPVdQ0QAMQqLFy+MZyiZMRMjmIXxailEmg4hDI+je-EskLgmm+sxIMHg5ARTGIigBXFmfyYAHcpABraFMIrYzTEKwQYgyD4QNayVoYfoDMSiO4EqDYUQQc6OMkEuJsFRNVBQCBwRwBEhaOIcUh3CJgEFkVlOQbJGqIfTCsii7wSqUyuXg2JKxwquUsYjODCA3xhNU1JgAHzdMQqcG1uuePQAAhptHQMFSCRBAVBNF0ej1CkVpUkwAARYgRqOaYbdONRfrQeDJrFkFm7A6LHNRJ49bQ0JjhyPEaMDMI6pY9fqIHEsMjAeaudyHd1MABypFmCWZig1zhb1dzYjr-Q5o-HfoXcaEZHkdG6Y6l9Q32A40sRyQoPeS+jAAF9DkA](url)

**Comment by wch** [comment]
I think you're running into one of the oddities of way file inputs work in Shiny. On the python side, `input.file1()` changes when you upload a file. However, on the JS side, `input.file1` does not change. This is because the file uploading mechanism is quite a bit different from other inputs. (Also, the value of `input.file1()` in Python includes a path on the server, but obviously on the JS side we can't do that.)

This is your code:

```py
from shiny.express import input, ui, render
from shiny.types import FileInfo

ui.page_opts(
    title="Example",
    fillable=True,
)


ui.input_file(
    "file1",
    "Choose File",
    accept=[".csv"],
    multiple=False,
)

# using this to log inputs dict
# expected the commented out line to work
# but does not since input.file1 is always null
# with ui.panel_conditional("input.file1"):
with ui.panel_conditional("console.log(input) || true"):

    @render.download(
        label="Download",
        filename="output.csv",
    )
    def download1():
        file: list[FileInfo] | None = input.file1()
        if file is None:
            return None

        yield "test"
```

Here is one way to accomplish what you're trying to do, using `render.ui()`:

```py
from shiny.express import input, ui, render
from shiny.types import FileInfo

ui.page_opts(
    title="Example",
    fillable=True,
)


ui.input_file(
    "file1",
    "Choose File",
    accept=[".csv"],
    multiple=False,
)


@render.ui
def download_ui():
    file: list[FileInfo] | None = input.file1()
    print(f"input.file1(): {file}")
    if file is None:
        return

    return download_button_ui


with ui.hold() as download_button_ui:

    @render.download(
        label="Download",
        filename="output.csv",
    )
    def download():
        yield "test"
```


One thing about this is that it calls `@render.download` unconditionally -- what is conditional is whether the UI from `@render.download` is displayed, via the `@render.ui`.

This is a case where Shiny Core syntax is probably a bit easier to understand than Shiny Express. In Shiny Express, the `@render.download` creates the server-side handler _and_ the UI element, but then the UI element is saved for use elsewhere. In Shiny core, the server and UI components are always created separately, which would be a bit easier to understand in this case, in my opinion.

**Comment by roivant-matts** [comment]
Thanks! Yes, a but confusing, but happy to have a solution.
