### ISSUE TITLE
App with no outputs never stops pulsing

### ISSUE THREAD

**Issue by jcheng5** [posit-dev/py-shiny#1398]
Example:

```python
# pyright:basic
from shiny.express import input, render, ui, module

ui.input_action_button("minus", "-")
ui.input_action_button("plus", "+")
```
[shinylive](https://posit-dev.github.io/py-shiny/shinylive/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAHQjoGIACHAJwEsBzACzMQCMoAZ3aE6AM1bEYTId3YRsGOAA9UrOEKFN2MVMVZkdEVAFcyeJhogATOK0un2lmMRumANnDp0nGBWZkAPpQhGTspEH85mSkABQ0YDAKpkKJlokAtIkAlL7s-ibmIWEREFEx8YmoHqnpTIkA1Ll0YAC+ALpAA)

**Comment by cpsievert** [comment]
Great catch! This happens because we currently [wait until the first idle](https://github.com/rstudio/shiny/blob/main/srcts/extras/busy-indicators/busy-indicators.ts) to clear the "initial busy status". 

I was hoping to use that event to avoid abrupt removal/addition of the pulse in between `shiny:connnected`/`shiny:sessioninitialized` and `shiny:busy`, but I suppose we should use the former instead?
