### ISSUE TITLE
`ui.output_ui()` isn't a fill item or fillable container by default, leads to inconsistent layout when using dynamic UI

### ISSUE THREAD

**Issue by vindevoy** [posit-dev/py-shiny#1615]
This is my initial code:

```
from pathlib import Path

from shiny import App, ui, render

left_sidebar = ui.sidebar("Left Sidebar", id="left_sidebar", bg="#f8f8f8")
right_sidebar = ui.sidebar("Right Sidebar", id="right_sidebar", bg="#f8f8f8", position="right")
main_content = ui.output_ui(id="render_main")
right_part = ui.layout_sidebar(
                    right_sidebar, main_content, padding=[20, 50, 20, 50], id="right_part", border=False)

app_ui = ui.page_fillable(
            ui.layout_sidebar(
                left_sidebar,
                right_part,
                padding=0,
                id="left_sidebar_holder",
                border=False,
                border_radius=False
            ),
            id="page_main",
            title="Shiny Pivot",
            padding=0,
        )


def server(inputs, outputs, session):
    assert inputs is not None
    assert outputs is not None
    assert session is not None

    @render.ui
    def render_main():
        card = ui.card(
            ui.h1("Reporting"),
            ui.p(f"left_sidebar: {inputs.left_sidebar()}"),
            ui.p(f"right_sidebar: {inputs.right_sidebar()}"),
        )

        return card


app = App(app_ui, server, static_assets=Path(__file__).parent.parent.joinpath("pivot", "static"))
```

This renders into:

![image](https://github.com/user-attachments/assets/857728b4-833b-4858-9e8b-a02e139a06b5)

The above is what I expected.  However, when I change my code to return the left_part from within the server function like this:

```
from pathlib import Path

from shiny import App, ui, render

left_sidebar = ui.sidebar("Left Sidebar", id="left_sidebar", bg="#f8f8f8")
right_sidebar = ui.sidebar("Right Sidebar", id="right_sidebar", bg="#f8f8f8", position="right")
main_content = ui.output_ui(id="render_main")
right_part = ui.layout_sidebar(
                    right_sidebar, main_content, padding=[20, 50, 20, 50], id="right_part", border=False)

app_ui = ui.page_fillable(
            ui.output_ui("left_part"),
            id="page_main",
            title="Shiny Pivot",
            padding=0,
        )


def server(inputs, outputs, session):
    assert inputs is not None
    assert outputs is not None
    assert session is not None

    @render.ui
    def left_part():
        return ui.layout_sidebar(
            left_sidebar,
            right_part,
            padding=0,
            id="left_sidebar_holder",
            border=False,
            border_radius=False
        ),

    @render.ui
    def render_main():
        card = ui.card(
            ui.h1("Reporting"),
            ui.p(f"left_sidebar: {inputs.left_sidebar()}"),
            ui.p(f"right_sidebar: {inputs.right_sidebar()}"),
        )

        return card


app = App(app_ui, server, static_assets=Path(__file__).parent.parent.joinpath("pivot", "static"))
```

All of a sudden, my sidebars are shrunk.

![image](https://github.com/user-attachments/assets/d1187d54-a786-4701-9639-a954da702d85)

**Comment by gadenbuie** [comment]
Hi @vindevoy -- the way around this is to turn on `fill` and `fillable` in `ui.output_ui("left_part")` so that the ui output has the same filling behavior as `ui.layout_sidebar()`:

```
ui.output_ui("left_part", fill=True, fillable=True),
```

Here's an example on [shinylive.io](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACVKMgCwBsBLAIye4xUxOmSYAFNuwA6EWfUZMAzu24RsAoSLEBBdHiYBXbgbqUAJnDqzZnODTIB9Jd0u8odJgF4j3DC7cPAAppMAAZezEAZVc4d2t8AXMvULsHZ1j40INeAHMUsABiGgAOUtLQgEpZOm5c9icAuI9vX39M4NCAJTqGphjAhINXAtr6xo6hpjyC4rL57JZiFzJuUlHesirZGCg1RxJySjEfYwxiQzJUS8djIJHQswhLOkddtW2IMYbHVlFWs6cKDYC4TQYhCBMKHQmGw2HfMHNOgGd4QA6kCjkAysczmNT5YAAJgADAYAKykpgk8nEgC6w2Sj02vw8W0SvBELy8ADEoJwlHBqnJoOhbtwAX5WLk4I4aNxOEDeHYIXC4WdQdcnHdUpEWaJFnKFV4ACp0QxwAyGxV2E1mwV4WSq2EPMBSmWo7KOp3Q1ZkG2hKKqdQSbgAN2IbIdkO9UJxeIg+VJXrhQpsz3syisoas9wgmqUBg1lwLmaULlIlUQyaYUDLVjEanzAiUTAgEaYADlSHBq7WBf8i2QW9wW22xF2ID3o1C+-XS+XISPW+2J1PqwABJ4vDB3IUwyw0JhpJx-MhBSvVmFmMiGOiQwHA0EZcGX1XH59IqMxqEIvVkL-fnG+JeEm07ei675NPEjjsMQnAvJ6YFOhydBcry-IWq+cIoS8jh0FAeKGEoPJ8gKWFMJUUYbluVg7tw1YHkwNGvKi55Vkh0KEB45gShgXGoSq35nOwACMIRgF0cDCKI+JVABMZnKgQQ0Dq6RQR4iBMCAjbFhgkGTOeAC+cnkTCinKUy4wfvEmnaXmum-updBGSZHFQqmblMXAN53kw-HmGmshoKgrR6EpwVigY-bZsiyhkGw3CEI4s5Dl4kgcEEjiyvKMqOJUWAeMcBVPGQGAAFbEI2UjiagYYRosoRKPFqyEFUlRgIZtJAA).

**Comment by vindevoy** [comment]
Thanks, that fixes it.
