### ISSUE TITLE
Module.server to server eval of a looped string

### ISSUE THREAD

**Issue by codezilla451** [posit-dev/py-shiny#503]
Very possible that I am implementing this incorrectly between the @module.server to server but I do not understand why I am unable to eval a loop driven string? When calling a defined server input value directly in a dictionary the values are evaluated correctly. When forming a string and then using eval the input is not defined unless "defined" or "called" in a separate dictionary but defeats the purpose of capturing data from an unknown amount of modules to be added by the user interface.

The first time this is run it works correctly with eval.
```
Submit button selected 1 times
Check 1: in current values function 1
```

The eval cannot be completed without having a separate dictionary that has the shared_value_server breaking the dynamic ablility to add a module server?
```
 print(f"Check {i}: in current values function {eval(s)}")
                                                   ^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'inChk1' is not defined
```

mod.py
```
from shiny import *


@module.ui
def shared_values_ui(name):
    return ui.TagList(
        ui.h3(name),
        ui.row(
            ui.column(
                2, ui.input_numeric("in_check_num", label="Check Number", value=0)
            ),
            ui.column(
                2, ui.input_numeric("in_check_amount", label="Check Amount", value=0)
            ),
            ui.column(
                2,
                ui.input_checkbox_group(
                    "in_check_tips",
                    label="Check Tips?",
                    choices=["Usergroup 1", "Usergroup 2"],
                ),
            ),
            ui.column(
                2,
                ui.input_numeric("in_check_tips_amount", label="Tips Amount", value=0),
            ),
            ui.column(3, ui.input_text_area("in_check_notes", label="Notes")),
        ),
    )


@module.server
def shared_values_server(input, output, session):
    return input
```
app.py
```
from shiny import *

from mod import *

app_ui = ui.page_fluid(
    {"id": "main-content"},
    ui.row(
        ui.input_selectize(
            "in_submitted_by",
            label="Checks Submitted By:",
            choices=["User 1", "User 2", "User 3"],
        ),
        ui.input_date("in_date", label="Date"),
    ),
    ui.row(
        ui.column(3, ui.input_action_button(id="button2", label="Add Check")),
        ui.column(3, ui.input_action_button(id="button1", label="Submit Checks")),
    ),
)


def server(input, output, session):
    inChk1 = shared_values_server("chk1")
    inChk2 = shared_values_server("chk2")
    inChk3 = shared_values_server("chk3")

    @reactive.Calc
    def current_values():
        chk_current_dict = {}
        chk_current_dict_fails = {}
        for i in range(input.button2()):
            i += 1
            in_chk_num = f'inChk{str(i)}["in_check_num"]()'
            in_chk_amt = f'inChk{str(i)}["in_check_amount"]()'
            in_chk_tips = f'inChk{str(i)}["in_check_tips"]()'
            in_chk_tips_amt = f'inChk{str(i)}["in_check_tips_amount"]()'
            in_chk_notes = f'inChk{str(i)}["in_check_notes"]()'
            # This is the dictionary that I would like to have dynamically created based on the number of checks added
            chk_current_dict_fails[f"inChk{i}"] = {
                "submitted_by": f"{input.in_submitted_by}",
                "date": f"{input.in_date()}",
                "in_check_num": str(eval(in_chk_num)),
                "in_check_amt": str(eval(in_chk_amt)),
                "in_check_tips": str(eval(in_chk_tips)),
                "in_check_tips_amt": str(eval(in_chk_tips_amt)),
                "in_check_notes": str(eval(in_chk_notes)),
            }
        # This dictionary is necessary to get the input from the checks but would require a lot of repetition to get the data and would not be dynamic or even work without knowing how many checks are added ahead of time.
        chk_current_dict = {
            "data": {
                "submitted_by": f"{input.in_submitted_by()}",
                "date": f"{input.in_date()}",
            },
            "inChk1": {
                "check_num": f"{inChk1['in_check_num']()}",
                "check_amount": f"{inChk1['in_check_amount']()}",
                "check_tips": f"{inChk1['in_check_tips']()}",
                "check_tips_amount": f"{inChk1['in_check_tips_amount']()}",
                "check_notes": f"{inChk1['in_check_notes']()}",
            },
            # "inChk2": {"check_num": f"{eval(s)}"},
            "inChk2": {"check_num": f"{inChk2['in_check_num']()}"},
            # "inChk3": {"check_num": f"{inChk3['in_check_num']()}"},
        }

        return chk_current_dict_fails

    @reactive.Effect
    @reactive.event(input.button2)
    def check_add():
        btn = input.button2()
        print(f"Add check button clicked: {btn}")
        if btn != 0:
            chkBtnUi = shared_values_ui(f"chk{btn}", f"Check #{btn}")
            ioutv = ui.output_text_verbatim(f"chk{btn}", placeholder=True)
            ui.insert_ui(
                ui.row({"id": f"ins_row_inChk{btn}"}, chkBtnUi),
                selector="#main-content",
                where="beforeEnd",
            )
            ui.insert_ui(
                ui.row({"id": f"ins_row_txt_inChk{btn}"}, ioutv),
                selector="#main-content",
                where="beforeEnd",
            )

    @reactive.Effect
    @reactive.event(input.button1)
    def button1():
        btn = input.button1()
        print(f"Submit button selected {btn} times")
        cur_val = current_values()
        print(cur_val)

    @output
    @render.text
    def chk1():
        print(f"Updating text for check 1")
        return f"Check #1 added check num: {inChk1['in_check_num']()}"

    @output
    @render.text
    def chk2():
        print(f"Updating text for check 2")
        return f"Check #2 added check num: {inChk2['in_check_num']()}"


app = App(app_ui, server, debug=True)


def main():
    run_app(app)


if __name__ == "__main__":
    main()

```
Thanks for any help. Very much like this project and what it can bring reactive python development.

**Comment by jcheng5** [comment]
Hi there, thanks for checking out Shiny!

I don't know why `eval()` isn't working here, but you should just about never need to use `eval()` in a Shiny app, especially not to manage modules.

A few other thoughts, and then my attempt.

1. Returning the `input` from a Shiny module is a common anti-pattern when people are getting started with Shiny modules. The idea of the module is to treat all of the inputs/outputs as implementation details of the module, and have the module server take well-defined inputs and outputs (which can be reactive).
2. When you have dynamic numbers of a component being rendered, you're always going to want to store them in some data structure (either a dict() or a list(), usually) instead of having them as individual variables.
3. Not sure if you realized this, but you can create outputs from inside of a `@reactive.Effect`, and give them dynamic names via `@output(name=...)`.

[Here is my attempt in shinylive](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACdOgS3KbZlWLrJap25ADoQx9RkwDOACw7YuPPgICC6PEzpwohMmwBucTdogATOHU0BXNmIkNmMYmaW9+M2VG1mA+gagAG2s4aV9bTTlvOD8A4NDfaUsjOntodHC2JgBeJlssKABzOF8aYLYzAAoxJlqmEBEwCsbEJkaYKA4AWhJySjJGgF88Grr8hgB3aog62by2DA5UazJEuEC4PTYALzhpuYO2pohE6wAjGDYyCj8z7EaRmcPZwKgz9ezGgGFZTYBraRMADK50u1xiTAAQthEA9Rs9aoRZMQ2IRQtlgI0AKpJOhMACMDyOOMsTAATETsbimABmRoAXUezwAlEzDvklitfGYoBRqsduby4ETXu9Ap8wAARIWNVnwphyp61cbEKby2b5EjBGAQSo0mwLTmrXT6Ui+M4rMikSoVCUW66kCn4Jiij6NVRmVw-f6yxXPTXEbW6-XzRYQZbGrZm+1W3W2xox0iE52u8WNEEXK5Mb2EAG+tm1RXMtJiCw0GTJSw28MrTTEFYRyKhaRsUjM2FKrShayBMiA3KBNjSMiVYviTsAAW0JsMcAwXyChHlZaYhGsdFMqziIWko47z20ZHXMxANEaHB+fxAFQAHkwANQEwYtJg30dMGh8LhmG+aO8cJhKGseA6CFSptGkHs+2ZZ9x1mKcdC2IwMAAURoGhNgGSdpyQuc4CMchqwjDBEwgMkx1mFckX+XwoE9Pd1TqCBSECYhCCCLtIN7aQ0meIQOBHd1PVXX5cyYUjV0HXMYllXjDggYCchdShwO7bjmQfAk5IOCCoOkDA0FQSgqiiHx-CCHc1joFJ9gRWozyIWQrwUmBn2dSDM3BW5sGyI0w1OTybnNbBNB5ChfJrMh-LC4VO1mZkx0YxEnMhMgICxLJclMmJzPiMJbEqBykWc4C3M0Bycz+JgAGIQBctyKMOVsVgMJT8nrMgI18Cgby3Swzl5bhCsaYq6tKolUFeNFkUCCw6GyAAVOgQkag4OQgXFVgKpK5hVKYGiaMwXwcjgwkmXwLycsbXKGTRitS9K2D9OyKw2PQ+AlaqOm6XoKFEfAdtmCZfm0O04E-bQUPMOE4rqVbdsNDbLC2thbLsvbKgO5okA-c8Nt8c6yF6i6IEva63OGLgOoMZ67KSN6rXmxovs6CAelIP6BgB2GDmByw4DBiG4Cho7uZZbS5gnDqIxtMxsiKq76tknmmAQ8xLAwHqsOeKinN8aWVgYlXZn4wiHKxVAwo4QomC1j8v2osTyeVl6mDiJTdO44AXK6fF6VHYAAHIOF8R2-l8FzA-pQG6kPY9cbASqavJpg6IsVww6YFzWhAOI3JLbDEP0ZC0IwvR5QQmdkPw-oiJWEjLSTeGV1I-EjeeM40qUvzW9HHbTZHByMzBcTG5menMIhEBO4gQZbe4UIXcONc6FypSV83XKdz7lXWAEyoV9yxLxzEQylPUVBKkMzIm2sywxzAYZwGgeBqGcMwsFwAhfv6ahJGYMg2BUDWzcCobMQRRQbAcFIOQChQEeAiEwd+PZjBdirrFNIE5kEbAwLYUs4NPDRFiBZBIBUX5wHbPKOOdAZj5AWkUAAMkOQSKt8iyBpJUchtMEYYEmGjBEAYgz8NdmSA0YYuouUsKifkIcw4R2AiKN4bpE6iSqgAOWAu8VIzptwCwAAzwxZAWARCwtTAV1DHA4ojQxGnkSBaReNQ6qNos4aw-1NCpglEnVQrj3FuxIdkAxliFTGP9KYwM5jhEvVEcEjUiMuphzOMQG8vhCgMGsJfWJhxHFyP0KgHiYtXaHE8d8VRTAFpsHyQAfhhkU5eyJUTokxGAEkdA0n1lQFpZ0VJLDtIyeSBkoSXrcKMcEwRkSsm1Bicbdk8SuSSPYIQGRJxcmVLCLAesfiSlgAqfkpgPjNlc00LowJIzDhnLWuEoRIZ1pdS1rRacyynE0WYhQApHilFpjAGo4gbz8w7W4cfMQWCXAoIwLiFI+DyzZWIXlKyNl5RGjrA2WsFZpAtlIJEUEVwgp3FaAuQIkC4DAGAIyGQZA6BkpiviiBbwNgkrJcOSlYhKGF3QfORcy4CGez7O3Q41CTzBMaB5MEuL7g4xFTinKdxRxDIOI0GKL4mWVBiqOC5cwcnOJci+PysitXAVlUKgUcjYBc1aLqlZziNluJHOq2YmqaJ5IKa0ZVFrnm5m6mstVcqNXGucU6lxZquCRX8qs-JLjDmGpmbUB1HrXmLxxm6uR8bdzqtglQuAR4aGcT0mIR+9IgA), taking these principles into account.

P.S. It was unclear to me from your example whether you preferred `submitted_by` and `date` fields to be duplicated on each of the individual sub-objects, or not; I assumed yes. If no, you could further clean up the `shared_values_server` by removing the `submitted_by` and `date` arguments.
