### ISSUE TITLE
Communicating between modules

### ISSUE THREAD

**Issue by gshotwell** [posit-dev/py-shiny#690]
Good question from [Discord](https://discord.com/channels/1109483223987277844/1142194880723038338) posted for visibility:

> I have an app that uses ui.navset_tab_card to hold multiple ui.nav elements, for which each ui.nav element's ui and server function content takes the form of a module (https://shiny.posit.co/py/docs/workflow-modules.html). What I want to do:
> 
> 1) Within a ui.nav module, can I navigate through the ui.navset_tab_card with the ui.update_navs function, even though ui.navset_tab_card is outside the scope of the ui.nav module.
> 
> 2) Can I access and manipulate specific ui elements within a module. For example, I want to run ui.update_text for a ui.output_text ui element within a module.

**Comment by GShotwell** [comment]
Modules exist in their own namespace, which is what allows you have multiple instantiations of module without causing namespace conflicts. As a result in order to have a module interact with its parent you need to explicitly communicate between the module's namespace and the parent namespace. There are generally two ways to do this:

1) Pass arguments from the parent to the child module
2) Return values from the module to the parent

In both cases you can communicate reactive values, and operate on them like you would other values.  Since you're trying to use `update` functions, you can pass and return the namespace IDs to accomplish your goals. The namespaced id can be retrieved with `session.ns()`

## Update tab from module
Since the tabset id exists at the parent level, we need to pass it from the parent to the module as an argument. Once we do that we can update the tabset from within the module.

```
    button_1 = tab_server(
        "counter1",
        tabset=session.ns("tab_set"),
        exit_tab="B",
    )
```

## Update button text from parent
To update the button text from the parent, we need to know the id of that element within the module namespace. An easy way of doing this is to return that value from the module with `return session.ns("button")`. Once you have that id, you can update its value from the parent like you would any other value. 

## Example app with both functions

```
from shiny import App, Inputs, Outputs, Session, module, reactive, render, ui


@module.ui
def tab_ui(label: str = "Increment counter") -> ui.TagChild:
    return ui.div(
        {"style": "border: 1px solid #ccc; border-radius: 5px; margin: 5px 0;"},
        ui.input_action_button(id="button", label=label),
    )


@module.server
def tab_server(input: Inputs, output: Outputs, session: Session, tabset, exit_tab):
    @reactive.Effect
    @reactive.event(input.button)
    def _():
        ui.update_navs(tabset, selected=exit_tab)

    return session.ns("button")


# =============================================================================
# App that uses module
# =============================================================================
app_ui = ui.page_fluid(
    ui.navset_tab_card(
        ui.nav("A", tab_ui("counter1", "Go to Tab B")),
        ui.nav("B", tab_ui("counter2", "Go to Tab A")),
        id="tab_set",
    ),
    ui.input_action_button("exclaim", "Add '!'"),
)


def server(input: Inputs, output: Outputs, session: Session):
    def go_to(tab):
        ui.update_navs(session.ns("tab_set"), selected=tab)

    button_1 = tab_server(
        "counter1",
        tabset=session.ns("tab_set"),
        exit_tab="B",
    )

    button_2 = tab_server(
        "counter2",
        tabset=session.ns("tab_set"),
        exit_tab="A",
    )

    @reactive.Effect
    @reactive.event(input.exclaim)
    def add_exclamations():
        ui.update_action_button(button_1, label="Go to Tab B!")
        ui.update_action_button(button_2, label="Go to Tab A!")


app = App(app_ui, server)
```
